# binder/environment.yml (Option A: modern stack)
name: chembl-report
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit>=2024.03
  - numpy>=2.0
  - pandas>=2.1
  - jupyterlab>=4
  - ipykernel
  - ipywidgets>=8
  - itables>=2.0
  - pillow
  - openpyxl
  - voila>=0.5
  - pip
  - pip:
      - chembl-webresource-client>=0.10
      - pubchempy>=1.0.4
      - py3Dmol>=2.0
      - tabulate>=0.9
