# binder/environment.yml
name: chembl-report
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - chembl-webresource-client
      - pandas
      - tabulate
      - voila
      - ipywidgets
      - itables
      - openpyxl   # for Excel export (.xlsx)

